Compile: main.c ./ListaLinhas/ListaLinhas.c ./Palavra/Palavra.c ./ListaPalavras/ListaPalavra.c ./Dicionario/Dicionario.c ./ListaDicionario/ListaDicionario.h
	gcc main.c ./ListaLinhas/ListaLinhas.c ./Palavra/Palavra.c ./ListaPalavras/ListaPalavra.c ./Dicionario/Dicionario.c ./ListaDicionario/ListaDicionario.c -o e
run:
	./e